version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
      POSTGRES_DB: myapp_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      NODE_ENV: development

      DATABASE_URL: postgresql://myappuser:myapppassword@db/myapp_development
    depends_on:
      - db

volumes:
  postgres_data:
